#Eureka Server

server:
    port: 8761

spring:
  application:
      name: eureka-server

eureka:
    client:
      # чтобы наш сервер Eureka не зарегистрировался сам с собой, мы установили свойство.
        fetch-registry: false
      # чтобы клиент не получал информацию реестра от Eureka Server
        register-with-eureka: false
